AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE
TINY_PROFILE = TRUE

DEBUG      = TRUE
DEBUG      = FALSE

# DIM        = 2
DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
